# Generated by Django 2.2.13 on 2021-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default=models.CharField(max_length=100), max_length=200),
        ),
    ]
